driver:
  name: vagrant


provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: true

verifier:
  name: inspec
  format: junit
  output: '%{platform}_%{suite}_inspec.xml'

transport:
  name: winrm

platforms:
  - name: win10
    os_type: windows
    shell_type: powershell
    #attributes:


suites:
  - name: default
    run_list:
      - recipe[ruby-windows::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
